# https://docs.kanboard.org/v1/admin/docker
# https://gist.github.com/dnburgess/03fc456e15ccdf90b9d80652d26fdbd4
# https://gitlab.open-mind.space/pandel/docker-kanboard/-/blob/master/docker-compose.yml

version: '3'
# Define container services.
services:
  # Define data store
  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: kb_db
      MYSQL_USER: osadmin
      MYSQL_PASSWORD: BGT5QRT=
    volumes:
      - db:/var/lib/mysql

  # Define Kanboard container.
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8080:80"
    environment:
      - PLUGIN_INSTALLER=true
      - DATABASE_URL=mysql://osadmin:BGT5QRT=@mariadb/kb_db
    restart: unless-stopped
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - /container/config.php:/var/www/app/config.php
    depends_on:
      - mariadb

  # Define reverse proxy.
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - /container/compose/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kanboard

# Define containers volumes.
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
  db:
    driver: local
