version: '3'
# Define container services.
services:
  # Define Kanboard container.
  kanboard:
    image: docker.io/kanboard/kanboard:latest
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://kanboard:kanboard-password@mariadb/kanboard
    restart: unless-stopped
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
    depends_on:
      - mariadb

  # Define reverse proxy.
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - /container/compose/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kanboard

  # Define data store
  mariadb:
    image: docker.io/mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: kb_db
      MYSQL_USER: osadmin
      MYSQL_PASSWORD: BGT5QRT=
    volumes:
      - db:/var/lib/mysql

# Define containers volumes.
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  db:
