# Compose version.
version: '3'

# Container definitions.
services:

  # Portainer container.
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-network

  # Prometheus container.
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  # Grafana container.
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitoring-network

  # Node Exporter.
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    networks:
      - monitoring-network

  # Docker agent.
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring-network

  # Portainer agent.
  portainer-agent:
    image: portainer/agent
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring-network

# Network definition.
networks:
  monitoring-network:
