version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.14.2
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /container:/data
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == portainer

  portainer_edge_agent_node1:
    image: portainer/agent:2.14.2
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - /container:/data
    environment:
      EDGE: "1"
      EDGE_ID: "898d7562-73cc-495d-abe2-9391b0b70ec9"
      EDGE_KEY: "aHR0cHM6Ly8xOTIuMTY4LjU2Ljc1Ojk0NDN8MTkyLjE2OC41Ni43NTo4MDAwfGQ0OjU2OjMyOjFmOjg5OjllOmQ0OjZhOjkxOjhmOjZlOmUyOmY5OmMzOjc0OmQxfDM"
      EDGE_INSECURE_POLL: "1"
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == node1

  portainer_edge_agent_node2:
    image: portainer/agent:2.14.2
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - /container:/data
    environment:
      EDGE: "1"
      EDGE_ID: "90207b21-8235-46c7-b332-e3dfdee04800"
      EDGE_KEY: "aHR0cHM6Ly8xOTIuMTY4LjU2Ljc1Ojk0NDN8MTkyLjE2OC41Ni43NTo4MDAwfGQ0OjU2OjMyOjFmOjg5OjllOmQ0OjZhOjkxOjhmOjZlOmUyOmY5OmMzOjc0OmQxfDQ"
      EDGE_INSECURE_POLL: "1"
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == node2

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /container
    deploy:
      placement:
        constraints:
          - node.hostname == node1
          - node.hostname == node2
